### ISSUE TITLE
set noUncheckedIndexedAccess: true

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/support-frontend#5829]
We gain far more security by having [`noUncheckedIndexedAccess: true`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in [our `tsconfig`](https://github.com/guardian/support-frontend/blob/main/support-frontend/tsconfig.json#L23).

```[tasklist]
### Tasks
- [x] https://github.com/guardian/support-frontend/pull/5828 1 assets/components/directDebit/helpers/ajax.ts:29
- [ ] 1  assets/components/forms/customFields/options.tsx:9
- [ ] 3  assets/components/forms/customFields/sortedOptions.tsx:10
- [ ] 1  assets/components/gridImage/gridImage.tsx:33
- [ ] 5  assets/components/headers/links/links.tsx:34
- [ ] 1  assets/components/paymentMethodSelector/PaymentMethodSelectorContainer.tsx:109
- [ ] 1  assets/components/paymentRequestButton/hooks/payerDetails.ts:27
- [ ] 1  assets/components/payPalPaymentButton/payPalButtonProps.ts:67
- [ ] 1  assets/components/subscriptionCheckouts/address/postcodeFinder.tsx:105
- [x] https://github.com/guardian/support-frontend/pull/5830 3 assets/components/subscriptionCheckouts/addressSearch/__tests__/addressResultsTests.ts:44
- [x] https://github.com/guardian/support-frontend/pull/5830 14 assets/components/subscriptionCheckouts/addressSearch/addressResultsHelpers.ts:9
- [ ] 1  assets/components/subscriptionCheckouts/paymentMethodSelector.tsx:189
- [ ] 1  assets/components/thankYou/signIn/signInItems.tsx:127
- [ ] 2  assets/components/thankYou/supportReminder/supportReminderItems.tsx:201
- [ ] 11 assets/helpers/abTests/abtest.ts:177 https://github.com/guardian/support-frontend/pull/5928
- [ ] 4  assets/helpers/abTests/helpers.ts:265
- [ ] 2  assets/helpers/campaigns/campaigns.ts:34
- [ ] https://github.com/guardian/support-frontend/pull/5831 23 assets/helpers/contributions.ts:181
- [ ] 1  assets/helpers/customHooks/useHasBeenSeen.ts:19
- [ ] 1  assets/helpers/forms/existingPaymentMethods/existingPaymentMethods.ts:134
- [ ] 3  assets/helpers/forms/paymentIntegrations/payPalRecurringCheckout.ts:96
- [ ] 1  assets/helpers/globalsAndSwitches/globals.test.ts:23
- [ ] 1  assets/helpers/images/theGrid.ts:23
- [ ] 2  assets/helpers/internationalisation/classes/country.ts:48
- [ ] 1  assets/helpers/redux/checkout/addressMeta/reducer.ts:35
- [ ] 1  assets/helpers/redux/checkout/payment/payPal/thunks.ts:49
- [ ] 1  assets/helpers/redux/checkout/payment/stripe/thunks.ts:25
- [ ] 1  assets/helpers/redux/checkout/personalDetails/subscriptionsSideEffects.ts:64
- [ ] 1  assets/helpers/redux/checkout/product/selectors/productType.ts:48
- [ ] 2  assets/helpers/redux/user/reducer.ts:14
- [ ] 3  assets/helpers/storage/cookie.ts:18
- [ ] 1  assets/helpers/subscriptionsForms/deliveryDays.ts:37
- [ ] 1  assets/helpers/subscriptionsForms/submit.ts:354
- [ ] 6  assets/helpers/tracking/acquisitions.ts:107
- [ ] 4  assets/helpers/tracking/googleTagManager.ts:198
- [ ] 1  assets/helpers/tracking/ophan.ts:98
- [ ] 1  assets/helpers/tracking/quantumMetric.ts:160
- [ ] 2  assets/helpers/tracking/thirdPartyTrackingConsent.ts:65
- [ ] 1  assets/helpers/urls/url.ts:42
- [ ] 1  assets/helpers/user/user.ts:77
- [ ] 8  assets/pages/aus-moment-map/ausMomentMap.tsx:54
- [ ] 1  assets/pages/aus-moment-map/components/map.tsx:24
- [ ] 6  assets/pages/aus-moment-map/components/testimonialsContainer.tsx:151
- [ ] 1  assets/pages/digital-subscriber-checkout/setup/setUpRedux.ts:84
- [ ] 1  assets/pages/paper-subscription-checkout/components/deliveryAgentsSelect.tsx:42
- [ ] 1  assets/pages/paper-subscription-checkout/components/paperCheckoutForm.test.tsx:131
- [ ] 15  assets/pages/paper-subscription-checkout/helpers/__tests__/deliveryDays.test.ts:108
- [ ] 3  assets/pages/paper-subscription-checkout/helpers/homeDeliveryDays.ts:19
- [ ] 1  assets/pages/paper-subscription-checkout/helpers/options.ts:50
- [ ] 1  assets/pages/paper-subscription-checkout/helpers/subsCardDays.ts:118
- [ ] 1  assets/pages/subscriptions-redemption/api.ts:249
- [ ] 1  assets/pages/supporter-plus-landing/setup/legacyActionCreators.ts:415
- [ ] 2  assets/pages/supporter-plus-landing/twoStepPages/threeTierLanding.tsx:246
- [ ] 2  assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.test.tsx:290
- [ ] 1  assets/pages/weekly-subscription-checkout/components/weeklyCheckoutForm.tsx:270
- [ ] 1  assets/pages/weekly-subscription-checkout/components/weeklyCheckoutFormGifting.test.tsx:122
- [ ] 3  assets/pages/weekly-subscription-checkout/helpers/__tests__/deliveryDays.ts:35
- [ ] 1  assets/pages/weekly-subscription-checkout/helpers/deliveryDays.ts:31
- [ ] 1  assets/pages/weekly-subscription-checkout/weeklySubscriptionCheckout.tsx:34
- [ ] 3  assets/pages/weekly-subscription-landing/weeklySubscriptionLanding.tsx:102
- [ ] 1  stories/checkouts/PaymentFrequencyTabs.stories.tsx:47
- [ ] 18 stories/screens/supporterPlusThankYou/AusSupporterPlusThankYou.stories.tsx:117 https://github.com/guardian/support-frontend/pull/5927
- [ ] 33 stories/screens/supporterPlusThankYou/ROWSupporterPlusThankYou.stories.tsx:109 https://github.com/guardian/support-frontend/pull/5927
```

**Comment by jamesgorrie** [comment]
@andrewHEguardian 🐘 task, well done!
