### ISSUE TITLE
Add Supporter Plus default promoCode

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/support-frontend#5897]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/support-admin-console/pull/567 Add optional `supporterPlus` to RRCP
- [ ] https://github.com/guardian/support-admin-console/pull/568 Make `supporterPlus` required in RRCP
- [ ] https://github.com/guardian/support-frontend/pull/5899 Read values from RRCP in `support-frontend`
```
